language: clojure

env:
  global:
    - GH_REF: github.com/hscells/hscells.github.io.git
    - GH_TOKEN: GXLPR2k0jhryJ3vLviW8l/OCga0CUhGbgkL3JIl0EXogcgjKTzDe+1kV0y3VXsK7v6wGMBeV99EKkXeyjsXMFFOugioHEKUrtxyPRBXauH4OC2tuxnPGsdEKrsqfFoqO+qRWeoSMi6QKC8eSJhWvp1xt+h4WY6CSULxSeEIG64s1VyELG2z72fBBsw9opxbnR0q+ZXnp1oqousAixP9Uh8mopaAOfmFI1EAFeuBYLNrVSWED/yaz5esSt9XELstfIKcnDedCwgt/gZVDilgm4AJUsSUVCL+VgtVuSchRzeVj/5tQ3qkIljzZisZmua/wHlKMvbJaxf60fd+BrpH7UgfJE9onZvHvearP5qWFUkjcjkAw014fpR+WCJtt6hwLzQzV4iSIJZ3htX318PH03St75Nb2Ib3pC6pw97CGcwcD7CZ6XGBVQDKyPDuuJDHig0YhZO0WCUurkEu0SiL0VoyFliVk7Og/ZnZT0W05+nQaA5lpuGGG5x9X4OrPlW0bEYExQM1PcsJ57DCPwPmEwwi+XjYtwGAjyyDvzcHmb/YMqylBSc89P3L3Z7gEX24282varQdlKOZcWKDxYhJ6jBkkgDNdeoySu6SoLSXGio3DwJq3frDZdropPLQw7bT16RI7ednDppgsf1Ge1fNh9oCeg11UZ+BFUHXqUrWyajs=
    - secure: GXLPR2k0jhryJ3vLviW8l/OCga0CUhGbgkL3JIl0EXogcgjKTzDe+1kV0y3VXsK7v6wGMBeV99EKkXeyjsXMFFOugioHEKUrtxyPRBXauH4OC2tuxnPGsdEKrsqfFoqO+qRWeoSMi6QKC8eSJhWvp1xt+h4WY6CSULxSeEIG64s1VyELG2z72fBBsw9opxbnR0q+ZXnp1oqousAixP9Uh8mopaAOfmFI1EAFeuBYLNrVSWED/yaz5esSt9XELstfIKcnDedCwgt/gZVDilgm4AJUsSUVCL+VgtVuSchRzeVj/5tQ3qkIljzZisZmua/wHlKMvbJaxf60fd+BrpH7UgfJE9onZvHvearP5qWFUkjcjkAw014fpR+WCJtt6hwLzQzV4iSIJZ3htX318PH03St75Nb2Ib3pC6pw97CGcwcD7CZ6XGBVQDKyPDuuJDHig0YhZO0WCUurkEu0SiL0VoyFliVk7Og/ZnZT0W05+nQaA5lpuGGG5x9X4OrPlW0bEYExQM1PcsJ57DCPwPmEwwi+XjYtwGAjyyDvzcHmb/YMqylBSc89P3L3Z7gEX24282varQdlKOZcWKDxYhJ6jBkkgDNdeoySu6SoLSXGio3DwJq3frDZdropPLQw7bT16RI7ednDppgsf1Ge1fNh9oCeg11UZ+BFUHXqUrWyajs=

before_script:
  - git config --global user.email "harryscells@gmail.com"
  - git config --global user.name "Travis-CI"
  - git config --global push.default matching

after_script:
  - git clone https://github.com/hscells/hscells.github.io.git
  - lein doc
  - cd hscells.github.io
  - git add *
  - git commit -m "updated health-search doc"
  - git push --force "https://${GH_TOKEN}@${GH_REF}"

before_deploy:
  - lein uberjar
  - export RELEASE_PKG_FILE=$(ls target/uberjar/*.jar)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: Iz7pvNS+uyYes5Q6KBWSSIWjed3MLZBNbM9Wq1jTV3XGHj6S6bYGIH1umUnVdlFvfzlFf30h5XQsRkEuoUQIohpADu4+6v3xt/JaM6gyg7z9J5wbqb3A2Pz+EdMTRiHT348HwHK+QrPSXXXj6VW+/Xyha/44Iv3t7QNiYXUueVLsjF2mbRISOE5AO2YdO7Wn+/ZuYNbkzcN9/U41sej0M8VV7ebCaawSm9I86imQn/A3plniEOs+aCkrFLI4At4HCTVTyuK0xmIdtst/gUsUm0EKHChCxjrj9FNe2GLcaSKV6lWPOQ4Bj8WazPrGIEYY5wrPvZFgBKbPlanXhXpL+K0TD7E1esUJ3aFnTm4n6iC37B8VYZ6YFOoZJ3kGPibwd+7CQEb0apS4Nj3tfkKvfhV9v8xfvJwYuz07TkTgXiWE/Zu7vu7Sat94J7CKbInmuxonlDwjpT+4p4qdlPPyeyW8cLj3uBAu2XRbRFtcKgQ/rGarx0WhZRT3zvaYp6KOUQ8BFwGLhC3WMsQxnJb6y/qp375gAj8JRBOeqk4a5XwhChXGDeaBDUY2Ibw0HhZVjS1RPF8IsKuyT9INbWMTXl2ifzT4HrNiXcSxen2TleeGcoCqjJEqSVbHqKeoiD0TaQhVy1DHoRaRDjqd5wXnGHEi+B15+ui2qINQM98HYuc=
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  on:
    tags: true
